# Generated by Django 4.2.14 on 2024-07-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biograpy', models.CharField(max_length=300, null=True)),
                ('linkone', models.URLField()),
                ('defone', models.CharField(max_length=300)),
                ('linktwo', models.URLField()),
                ('deftwo', models.CharField(max_length=300)),
                ('linkthree', models.URLField()),
                ('defthree', models.CharField(max_length=300)),
            ],
        ),
    ]
