# Generated by Django 4.2.14 on 2024-08-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createlinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkset',
            name='biograpy',
        ),
        migrations.AddField(
            model_name='linkset',
            name='biography',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='defone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='defthree',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='deftwo',
            field=models.CharField(max_length=30),
        ),
    ]
