# Generated by Django 5.1 on 2024-08-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createlinks', '0004_linkset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkset',
            name='biography',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='defone',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='defthree',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='deftwo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='linkone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='linkthree',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='linkset',
            name='linktwo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
